
services:
  cataloguedb:
    image: postgres

  basketdb:
    image: postgres

  distributedcache:
    image: redis

  catalogue.api:
    image: ${DOCKER_REGISTRY-}catalogueapi
    build:
      context: .
      dockerfile: Services/Catalogue.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket.API/Dockerfile

volumes:
  postgres_catalogue:    
  postgres_basket:

